"""Generate solver entrypoints from a structured optimization problem spec."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from textwrap import dedent

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from problem_spec import OptimizationProblemSpec, load_problem_spec
else:
    from .problem_spec import OptimizationProblemSpec, load_problem_spec


def generate_solver_entrypoint(
    spec: OptimizationProblemSpec,
    out_dir: str | Path,
    solver_override: str | None = None,
) -> dict[str, str]:
    """Generate a supported solver wrapper and return route metadata."""

    route = spec.route(solver_override=solver_override)
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    if route["solver"] == "sdpt3":
        entrypoint = out_path / route["entrypoint"]
        entrypoint.write_text(_sdpt3_matlab_wrapper(spec))
    else:
        raise ValueError(f"code generation is not available for solver '{route['solver']}'")

    route = dict(route)
    route["entrypoint_path"] = str(entrypoint)
    route["candidate_command"] = route["candidate_command"].replace(route["entrypoint"], str(entrypoint))
    (out_path / "solver_route.json").write_text(json.dumps(route, indent=2, sort_keys=True) + "\n")
    return route


def _sdpt3_matlab_wrapper(spec: OptimizationProblemSpec) -> str:
    data_file = _matlab_path_expression(spec.data.get("mat_file", "problem.mat"))
    variables = spec.sdpt3.get("data_variables", {})
    blk_name = variables.get("blk", "blk")
    at_name = variables.get("At", "At")
    c_name = variables.get("C", "C")
    b_name = variables.get("b", "b")
    solver = spec.sdpt3.get("solver", "sdpt3")
    startup_path = spec.sdpt3.get("startup_path")
    result_file = f"../results/{spec.problem_id}_sdpt3_result.mat"

    option_lines = []
    for key, value in sorted((spec.sdpt3.get("options") or {}).items()):
        option_lines.append(f"OPTIONS.{key} = {_matlab_literal(value)};")
    options_block = "\n".join(f"    {line}" for line in option_lines) or "    % Default SDPT3 options."

    startup_block = ""
    if startup_path:
        startup_block = f"\n    run({_matlab_string(startup_path)});\n"

    return dedent(
        f"""
        function result = run_{spec.problem_id}_sdpt3()
        % Generated by optimization_solver_skill. Review and approve before execution.
            root_dir = fileparts(mfilename('fullpath'));
            results_dir = fullfile(root_dir, '..', 'results');
            if ~exist(results_dir, 'dir')
                mkdir(results_dir);
            end
        {startup_block}
            data_file = {data_file};
            loaded = load(data_file, '{blk_name}', '{at_name}', '{c_name}', '{b_name}');
            blk = loaded.{blk_name};
            At = loaded.{at_name};
            C = loaded.{c_name};
            b = loaded.{b_name};

            OPTIONS = sqlparameters;
        {options_block}
            [obj, X, y, Z, info, runhist] = {solver}(blk, At, C, b, OPTIONS);
            save(fullfile(root_dir, { _matlab_string(result_file) }), 'obj', 'X', 'y', 'Z', 'info', 'runhist');
            result = struct('obj', obj, 'info', info);
        end
        """
    ).lstrip()


def _matlab_string(value: object) -> str:
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def _matlab_path_expression(value: object) -> str:
    path = Path(str(value))
    if path.is_absolute():
        return _matlab_string(value)
    return f"fullfile(root_dir, {_matlab_string(value)})"


def _matlab_literal(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return _matlab_string(value)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", required=True, help="YAML or JSON optimization problem spec")
    parser.add_argument("--out", required=True, help="Output directory for generated entrypoint")
    parser.add_argument("--solver", default=None, help="Optional solver override")
    args = parser.parse_args()

    route = generate_solver_entrypoint(load_problem_spec(args.spec), args.out, args.solver)
    print(json.dumps(route, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
