"""Generate solver entrypoints from a structured optimization problem spec."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from textwrap import dedent

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from problem_spec import OptimizationProblemSpec, load_problem_spec
else:
    from .problem_spec import OptimizationProblemSpec, load_problem_spec


def generate_solver_entrypoint(
    spec: OptimizationProblemSpec,
    out_dir: str | Path,
    solver_override: str | None = None,
) -> dict[str, str]:
    """Generate an SDPT3 or CDOpt wrapper and return route metadata."""

    route = spec.route(solver_override=solver_override)
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    if route["solver"] == "sdpt3":
        entrypoint = out_path / route["entrypoint"]
        entrypoint.write_text(_sdpt3_matlab_wrapper(spec))
    elif route["solver"] == "cdopt":
        entrypoint = out_path / route["entrypoint"]
        entrypoint.write_text(_cdopt_python_wrapper(spec))
    else:
        raise ValueError(f"code generation is not available for solver '{route['solver']}'")

    route = dict(route)
    route["entrypoint_path"] = str(entrypoint)
    route["candidate_command"] = route["candidate_command"].replace(route["entrypoint"], str(entrypoint))
    (out_path / "solver_route.json").write_text(json.dumps(route, indent=2, sort_keys=True) + "\n")
    return route


def _sdpt3_matlab_wrapper(spec: OptimizationProblemSpec) -> str:
    data_file = _matlab_string(spec.data.get("mat_file", "problem.mat"))
    variables = spec.sdpt3.get("data_variables", {})
    blk_name = variables.get("blk", "blk")
    at_name = variables.get("At", "At")
    c_name = variables.get("C", "C")
    b_name = variables.get("b", "b")
    solver = spec.sdpt3.get("solver", "sdpt3")
    startup_path = spec.sdpt3.get("startup_path")
    result_file = f"../results/{spec.problem_id}_sdpt3_result.mat"

    option_lines = []
    for key, value in sorted((spec.sdpt3.get("options") or {}).items()):
        option_lines.append(f"OPTIONS.{key} = {_matlab_literal(value)};")
    options_block = "\n".join(f"    {line}" for line in option_lines) or "    % Default SDPT3 options."

    startup_block = ""
    if startup_path:
        startup_block = f"\n    run({_matlab_string(startup_path)});\n"

    return dedent(
        f"""
        function result = run_{spec.problem_id}_sdpt3()
        % Generated by optimization_solver_skill. Review and approve before execution.
            root_dir = fileparts(mfilename('fullpath'));
            results_dir = fullfile(root_dir, '..', 'results');
            if ~exist(results_dir, 'dir')
                mkdir(results_dir);
            end
        {startup_block}
            data_file = {data_file};
            loaded = load(data_file, '{blk_name}', '{at_name}', '{c_name}', '{b_name}');
            blk = loaded.{blk_name};
            At = loaded.{at_name};
            C = loaded.{c_name};
            b = loaded.{b_name};

            OPTIONS = sqlparameters;
        {options_block}
            [obj, X, y, Z, info, runhist] = {solver}(blk, At, C, b, OPTIONS);
            save(fullfile(root_dir, { _matlab_string(result_file) }), 'obj', 'X', 'y', 'Z', 'info', 'runhist');
            result = struct('obj', obj, 'info', info);
        end
        """
    ).lstrip()


def _cdopt_python_wrapper(spec: OptimizationProblemSpec) -> str:
    objective = spec.cdopt.get("objective") or {}
    manifold = spec.cdopt.get("manifold") or {}
    backend = spec.cdopt.get("backend", "torch")
    module = objective.get("module")
    function = objective.get("function")
    beta = spec.cdopt.get("beta", 100)
    summary_file = f"../results/{spec.problem_id}_cdopt_summary.json"

    return dedent(
        f'''
        """Generated CDOpt entrypoint for {spec.problem_id}.

        Review and approve before execution. This wrapper expects the objective
        module to be importable from the approved working directory.
        """

        from importlib import import_module
        import json
        from pathlib import Path


        def _require(value, label):
            if not value:
                raise SystemExit(f"Missing required CDOpt spec field: {{label}}")
            return value


        def main():
            try:
                import cdopt  # noqa: F401
                from cdopt.core.problem import problem
            except ModuleNotFoundError as exc:
                raise SystemExit("Missing dependency 'cdopt'. Ask for approval before installing it.") from exc

            backend = {backend!r}
            manifold_type = _require({manifold.get("type")!r}, "cdopt.manifold.type")
            objective_module = _require({module!r}, "cdopt.objective.module")
            objective_function = _require({function!r}, "cdopt.objective.function")

            obj_mod = import_module(objective_module)
            obj_fun = getattr(obj_mod, objective_function)

            raise SystemExit(
                "CDOpt manifold construction requires confirmed modeling details. "
                f"Backend={{backend}}, manifold={{manifold_type}}, objective={{obj_fun.__name__}}, beta={beta}. "
                "Complete the generated adapter after a modeling checkpoint, then rerun with approval."
            )

            # The intended next step is:
            # M = <construct manifold_type from approved dimensions/backend>
            # problem_obj = problem(M, obj_fun, beta={beta!r})
            # Solve the resulting CDF with the approved SciPy/PyTorch/JAX optimizer.
            # Path({summary_file!r}).write_text(json.dumps({{"status": "completed"}}, indent=2))


        if __name__ == "__main__":
            main()
        '''
    ).lstrip()


def _matlab_string(value: object) -> str:
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def _matlab_literal(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return _matlab_string(value)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", required=True, help="YAML or JSON optimization problem spec")
    parser.add_argument("--out", required=True, help="Output directory for generated entrypoint")
    parser.add_argument("--solver", default=None, help="Optional solver override")
    args = parser.parse_args()

    route = generate_solver_entrypoint(load_problem_spec(args.spec), args.out, args.solver)
    print(json.dumps(route, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
